### ISSUE TITLE
Default sort of content items; ability to sort by title, created, or updated dates

### ISSUE THREAD

**Issue by cidilabs** [ucfopen/UDOIT#542] opened 2020-07-09 15:41 UTC
Reported by Khaled Musa of UMN: 

After a user scans a course,  we would like the pages to be displayed by page name by default, and allow the user to select to display the pages that have errors or suggestions on them by date created or date last edited as well.
Right now there is no rhyme or reason for what is being displayed.
I guess the sort can be applied to discussions, assignments and files as well if errors show up in these, but a good start would be in pages.

**Comment by bagofarms** [comment] 2020-07-10 15:03
Duplicate of #518

**Closed by bagofarms** 2020-07-10 15:03 UTC

**Comment by cidilabs** [comment] 2020-07-10 16:44
Sorry, should've checked for duplicates before submitting.
