### ISSUE TITLE
Table headers not required when role="presentation"

### ISSUE THREAD

**Issue by robfentress** [ucfopen/UDOIT#93] opened 2016-02-24 16:17 UTC
UDOIT flags a table as being in error if it does not contain table headers (`<th>`).  This rule should check whether or not `role="presentation"` has been used with the table and should only report it as an error if this role has not been set.  With ARIA, it is now okay to use tables for layout, if the `role` is set to `"presentation"` (as long as the table makes sense when linearized), since this strips out any semantics.

![screen shot 2016-02-24 at 11 09 44 am](https://cloud.githubusercontent.com/assets/9356499/13291973/e65a2f0e-dae7-11e5-8e7c-36dfa4efc4dc.png)

**Comment by bagofarms** [comment] 2018-03-02 15:03
This standard is in a rough draft state:  https://github.com/w3c/aria-practices/issues/182

When it is a published standard, we will merge Emily's code.

**Comment by bagofarms** [comment] 2021-04-23 06:36
I guess I never got back to this.  That particular issue I mentioned in 2018 is still open, but it looks role="presentation" for tables made it into the standard:  https://www.w3.org/TR/wai-aria-1.0/roles#presentation

I'll be reviewing Emily's code and seeing if it can still be merged after all these years.

**Comment by jasonmatos23-git** [comment] 2021-06-10 18:41
Found an issue that was likely caused by resolving this issue. In some cases (see image) th are not detected.
<img width="817" alt="Screen Shot 2021-06-10 at 2 36 12 PM" src="https://user-images.githubusercontent.com/58221112/121579361-a52a8900-c9f9-11eb-8291-c132f1e1389b.png">

**Closed** 2021-06-11 13:43 UTC
Labels: Blocked, enhancement
