### ISSUE TITLE
Number of total reported problems not matching detailed report

### ISSUE THREAD

**Issue by dthomasg** [ucfopen/UDOIT#143] opened 2016-04-26 16:47 UTC
Sometimes the reports are returning a total error count that doesn't match the number of errors that are detailed in the report body. So, I'm concerned that I'm getting unreliable data. Here's an example: 
[ENGL&101 Demo South Seattle_PagesOnly.pdf](https://github.com/ucfcdl/UDOIT/files/237078/ENGL.101.Demo.South.Seattle_PagesOnly.pdf)

**Comment by cooperfellows** [comment] 2016-05-04 15:30
This looks like the PDF generation stopped early. Are there any server level errors you can see in your logs? Does the original report that gets run provide the correct amount of errors and details?

**Comment by dthomasg** [comment] 2016-05-05 14:30
Thanks for responding. 

While it looks like it's a problem with the PDF generation, it's a problem with the report itself. The totals for this report say 89 errors and 6 suggestions, but it only provides details for 14 errors and one suggestion. 

Here's a screenshot: 
![screen shot 2016-05-05 at 7 29 34 am](https://cloud.githubusercontent.com/assets/18684603/15046152/39757e2c-1293-11e6-84ef-581b5694aad9.png)

**Comment by cooperfellows** [comment] 2016-05-05 14:34
Can you run the same report again and confirm the same issues? Also, do you have other reports that have been run in this course? If so, did you run them back to back?

**Comment by dthomasg** [comment] 2016-05-05 14:44
I've run the report several times, over the course of months, with the same problem. I've exported this course and sent it to a friend, who is running UDOIT from another server and another instance of Canvas, and another friend who is running UDOIT from the same server I am, but on a different instance of Canvas (we're in the same state consortium), and all show tha same problem. 

I have also seen this problem in another course, but that was a few months ago, and it no longer replicates in that course.

**Comment by bagofarms** [comment] 2016-05-05 14:47
Would I be able to get a copy of the "Plan: Week 7" file?  It's been a while since I was in that part of the code, but I believe detection of errors all happens at once, then the HTML for the page is generated, so the HTML generation is probably just getting stuck on something in that file.

**Comment by dthomasg** [comment] 2016-05-05 16:05
`<div style="width: 200px; float: left; border: 1px solid #000; background-color: #000; color: #fff; padding: 5px;">
<p><img src="/courses/981192/files/36554568/preview" alt="Image of Interstate 7 shield" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554568" data-api-returntype="File" /></p>
<h2><span style="font-size: large;"><strong>Overview for the Week:</strong></span></h2>
<p><strong>This is a light week. You need to complete your <a title="Analysis Essay: Peer Evaluation" href="/courses/981192/assignments/3664900" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664900" data-api-returntype="Assignment">Peer Evaluations</a> for Essay 3.&nbsp;</strong></p>
<p><strong>A bit of extra credit is available for completing the&nbsp;<a id="" title="Extra Credit: Course Evaluation" href="/courses/981192/assignments/3664904" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664904" data-api-returntype="Assignment">Course Evaluation</a>.&nbsp;<br /></strong></p>
<p><strong>As always, complete your&nbsp;<a id="" title="Journal Week 6" href="/courses/981192/discussion_topics/2691963" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/discussion_topics/2691963" data-api-returntype="Discussion">Journal</a>.&nbsp;<br /></strong></p>
<p><strong>And, finally, submit your <a title="Essay 3: Analysis Essay Final Draft" href="/courses/981192/assignments/3664889" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664889" data-api-returntype="Assignment">Final Draft of Essay 3.</a>&nbsp;</strong></p>
<p><strong>Then take a break! We're done. </strong></p>
<p><strong>Final grades will be posted no later than 8:00 p.m. on Monday, August 12.&nbsp;</strong></p>
</div>
<div style="padding-left: 230px;">
<h2><strong>Weekly Plan: Week 7, August 5-8</strong></h2>
<h3>Readings</h3>
<ul>
<li>Read the essays of the people you were assigned for <a title="Analysis Essay: Peer Evaluation" href="/courses/981192/assignments/3664900" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664900" data-api-returntype="Assignment">Peer Evaluation</a>.&nbsp;</li>
</ul>
<hr style="border: 2px solid #000;" />
<h3>Assignments</h3>
<ul>
<li>Complete your <a id="" title="Analysis Essay: Peer Evaluation" href="/courses/981192/assignments/3664900" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664900" data-api-returntype="Assignment">Peer Evaluations</a> by 9 a.m. on Tuesday</li>
<li>If you'd like a bit of extra credit, complete an <a title="Extra Credit: Course Evaluation" href="/courses/981192/assignments/3664904" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664904" data-api-returntype="Assignment">anonymous evaluation of this course</a> (and submit a screenshot to prove that you did it) by 3:30 p.m. on Wednesday.&nbsp;</li>
<li>Submit your&nbsp;<a id="" title="Essay 3: Analysis Essay Final Draft" href="/courses/981192/assignments/3664889" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664889" data-api-returntype="Assignment">Essay 3: Analysis Essay Final Draft</a>&nbsp;by 9:30 a.m. on Thursday.</li>
</ul>
<hr style="border: 2px solid #000;" />
<h3>Journal</h3>
<ul>
<li>Complete <a id="" title="Journal Week 6" href="/courses/981192/discussion_topics/2691963" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/discussion_topics/2691963" data-api-returntype="Discussion">Journal Week 6</a>&nbsp;by Tuesday at 9 a.m.</li>
</ul>
<hr style="border: 2px solid #000;" /></div>
<p style="text-align: center;"><a title="Week 7 Support Discussion" href="/courses/981192/discussion_topics/2691950" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/discussion_topics/2691950" data-api-returntype="Discussion"><img src="/courses/981192/files/36554582/preview" alt="weeklysupport.png" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554582" data-api-returntype="File" /></a>&nbsp;<a title="List Of Weekly Plans" href="/courses/981192/wiki/list-of-weekly-plans" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/pages/list-of-weekly-plans" data-api-returntype="Page"><img src="/courses/981192/files/36554667/preview" alt="weeklyplans.png" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554667" data-api-returntype="File" /></a>&nbsp;<a title="Virtual Meeting Space" href="/courses/981192/wiki/virtual-meeting-space" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/pages/virtual-meeting-space" data-api-returntype="Page"><img src="/courses/981192/files/36554584/preview" alt="officehours.png" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554584" data-api-returntype="File" /></a></p>`

**Comment by dthomasg** [comment] 2016-05-05 16:06
<div style="width: 200px; float: left; border: 1px solid #000; background-color: #000; color: #fff; padding: 5px;">
<p><img src="/courses/981192/files/36554568/preview" alt="Image of Interstate 7 shield" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554568" data-api-returntype="File" /></p>
<h2><span style="font-size: large;"><strong>Overview for the Week:</strong></span></h2>
<p><strong>This is a light week. You need to complete your <a title="Analysis Essay: Peer Evaluation" href="/courses/981192/assignments/3664900" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664900" data-api-returntype="Assignment">Peer Evaluations</a> for Essay 3.&nbsp;</strong></p>
<p><strong>A bit of extra credit is available for completing the&nbsp;<a id="" title="Extra Credit: Course Evaluation" href="/courses/981192/assignments/3664904" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664904" data-api-returntype="Assignment">Course Evaluation</a>.&nbsp;<br /></strong></p>
<p><strong>As always, complete your&nbsp;<a id="" title="Journal Week 6" href="/courses/981192/discussion_topics/2691963" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/discussion_topics/2691963" data-api-returntype="Discussion">Journal</a>.&nbsp;<br /></strong></p>
<p><strong>And, finally, submit your <a title="Essay 3: Analysis Essay Final Draft" href="/courses/981192/assignments/3664889" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664889" data-api-returntype="Assignment">Final Draft of Essay 3.</a>&nbsp;</strong></p>
<p><strong>Then take a break! We're done. </strong></p>
<p><strong>Final grades will be posted no later than 8:00 p.m. on Monday, August 12.&nbsp;</strong></p>
</div>
<div style="padding-left: 230px;">
<h2><strong>Weekly Plan: Week 7, August 5-8</strong></h2>
<h3>Readings</h3>
<ul>
<li>Read the essays of the people you were assigned for <a title="Analysis Essay: Peer Evaluation" href="/courses/981192/assignments/3664900" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664900" data-api-returntype="Assignment">Peer Evaluation</a>.&nbsp;</li>
</ul>
<hr style="border: 2px solid #000;" />
<h3>Assignments</h3>
<ul>
<li>Complete your <a id="" title="Analysis Essay: Peer Evaluation" href="/courses/981192/assignments/3664900" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664900" data-api-returntype="Assignment">Peer Evaluations</a> by 9 a.m. on Tuesday</li>
<li>If you'd like a bit of extra credit, complete an <a title="Extra Credit: Course Evaluation" href="/courses/981192/assignments/3664904" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664904" data-api-returntype="Assignment">anonymous evaluation of this course</a> (and submit a screenshot to prove that you did it) by 3:30 p.m. on Wednesday.&nbsp;</li>
<li>Submit your&nbsp;<a id="" title="Essay 3: Analysis Essay Final Draft" href="/courses/981192/assignments/3664889" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/assignments/3664889" data-api-returntype="Assignment">Essay 3: Analysis Essay Final Draft</a>&nbsp;by 9:30 a.m. on Thursday.</li>
</ul>
<hr style="border: 2px solid #000;" />
<h3>Journal</h3>
<ul>
<li>Complete <a id="" title="Journal Week 6" href="/courses/981192/discussion_topics/2691963" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/discussion_topics/2691963" data-api-returntype="Discussion">Journal Week 6</a>&nbsp;by Tuesday at 9 a.m.</li>
</ul>
<hr style="border: 2px solid #000;" /></div>
<p style="text-align: center;"><a title="Week 7 Support Discussion" href="/courses/981192/discussion_topics/2691950" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/discussion_topics/2691950" data-api-returntype="Discussion"><img src="/courses/981192/files/36554582/preview" alt="weeklysupport.png" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554582" data-api-returntype="File" /></a>&nbsp;<a title="List Of Weekly Plans" href="/courses/981192/wiki/list-of-weekly-plans" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/pages/list-of-weekly-plans" data-api-returntype="Page"><img src="/courses/981192/files/36554667/preview" alt="weeklyplans.png" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554667" data-api-returntype="File" /></a>&nbsp;<a title="Virtual Meeting Space" href="/courses/981192/wiki/virtual-meeting-space" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/pages/virtual-meeting-space" data-api-returntype="Page"><img src="/courses/981192/files/36554584/preview" alt="officehours.png" data-api-endpoint="https://southseattle.instructure.com/api/v1/courses/981192/files/36554584" data-api-returntype="File" /></a></p>

**Comment by cooperfellows** [comment] 2016-05-05 16:08
I think having this content as an attachment will be easier to analyze. Can you provide the code like that instead?

**Comment by dthomasg** [comment] 2016-05-05 16:14
[div style= width  200px; float  left; border  1px solid #000; background-color  #000; color  #fff; padding  5px;.txt](https://github.com/ucfcdl/UDOIT/files/250710/div.style.width.200px.float.left.border.1px.solid.000.background-color.000.color.fff.padding.5px.txt)

**Comment by dthomasg** [comment] 2016-05-05 16:16
Sorry. I was working on my phone and the interface wasn't doing what I thought it would.

**Comment by bagofarms** [comment] 2016-05-05 17:43
Ok, i was able to confirm that my instance of UDOIT also halts on that page.  Now to figure out WHY it's happening.

**Comment by bagofarms** [comment] 2016-05-05 18:38
Here's the file.  If you make a page out of it, it seems to block rendering the rest of the report after the color contrast issue.
[error.txt](https://github.com/ucfcdl/UDOIT/files/250985/error.txt)

**Comment by cooperfellows** [comment] 2016-05-05 18:57
I've narrowed down the area where this is having trouble from the error logs:

` Fatal error:  Cannot use object of type stdClass as array in /app/public/parseResults.php on line 191`

[This is the relevant section.](https://github.com/ucfcdl/UDOIT/blob/master/public/parseResults.php#L191) I'm going to see if I can find anything, but won't be able to give it too much time today, just wanted to pass along what I've found so far.

**Comment by cooperfellows** [comment] 2016-05-05 21:31
I've got a much more trimmed down way to reproduce this issue:

`<h1 class="page-title">Plan: Week 7</h1><div style="width: 200px; float: left; border: 1px solid #000; background-color: #000000; color: #ffffff; padding: 5px;"><p><a title="Analysis Essay: Peer Evaluation" href="https://southseattle.instructure.com/courses/981192/assignments/3664900">Not Broken</a></p></div><div style="width: 200px; float: left; border: 1px solid #000; background-color: #000; color: #fff; padding: 5px;"><p><a title="Analysis Essay: Peer Evaluation" href="https://southseattle.instructure.com/courses/981192/assignments/3664900">Broken</a></p></div>`

I will have a more detailed bug report tomorrow, I'm getting close to having this solved.

**Comment by cooperfellows** [comment] 2016-05-06 19:53
I've got a guess as to what's going on here, and I think it's more of a bug in the Quail library than it is in anything UDOIT is trying to do.

**Background**

The main issue is that UDOIT tries to loop through an array that is supposed to contain the foreground and maybe background colors of elements that trigger the cssTestHasContrastRatio test. UDOIT stores these values as hidden form values used when UFIXIT is triggered.

In some cases, these colors are coming back as an object, not an array. So when we try to access the field values using `value="<?= $item->colors[$i]; ?>"` the bracket notation causes a Fatal Error, and processing stops.

You can see examples below of the object and array being output.

In this instance, the colors that we are trying to access in parseResults is an Object:
 - [Broken Example](http://screencast.com/t/naQq7MZp6ghK) (See output of $item during processing)

In other instances, the colors that we are trying to access comes to us as an Array:
 - [Working Example](http://screencast.com/t/pAPox58V86E) (See output of $item during correct processing)

**Potential Problem Root**

I believe the core issue lies in the regular expression that is being used to try to match hex values in the Quail library `/(#[0-9a-f]{6}|#[0-9a-f]{3})/`. This attempts to match a string of either 3 or 6 characters, but there is no limit on the number of matches that can be made.

If you look closely at the code below (which can be used to trigger this behavior), you will notice there are three hex values. A border color is also being defined.

`<h1 class="page-title">Plan: Week 7</h1><div style="width: 200px; float: left; border: 1px solid #000; background-color: #000000; color: #ffffff; padding: 5px;"><p><a title="Analysis Essay: Peer Evaluation" href="#">Not Broken</a></p></div><div style="width: 200px; float: left; border: 1px solid #000; background-color: #000; color: #fff; padding: 5px;"><p><a title="Analysis Essay: Peer Evaluation" href="#">Broken</a></p></div>`

Even more interesting is that when you use the full 6 character hex values for color (as I do in the "Not Broken" section of the example) none of these issues present themselves. It's only the shorthand causing a problem.

As that regular expression is run, three values get thrown into the $hexColors array that Quail uses to store these matches. 

Quail then goes on to assume that there is only ever either one or two matches, and takes the first and second values in the cases when there is more than one match:

`if ( sizeof($hexColors) === 1 ) {
								$testResult['fore_color'] = $hexColors[0];
							} else {
								$testResult['back_color'] = $hexColors[0];
								$testResult['fore_color'] = $hexColors[1];
							}`

Which clearly doesn't work in all cases.

**Potential Fix - Updated Regular Expression In Quail Library**
Since we are looking for font color (color:) and background color (background-color:) only, I'm thinking we could adjust the regular expression to the following:

`/(?:(?:background-)?color: ?)(#[0-9a-f]{6}|#[0-9a-f]{3})/`

This will capture only background and font color declarations, which actually resolves the current issue in my testing (that is report generation continues to function), but I think there are some deeper problems with this report writer in general. As the colors being returned aren't event correct. 

The links in the example here are blue on black (which is why the contrast error is thrown), and the font color being captured is white instead of blue. I believe this is due to the fact that the "color: #fff" declaration is an inline style, and the blue link color is declared in a CSS file. Which means that when the test runs, it's using the correct colors (blue on black) otherwise the contrast ratio of white on black would pass the test. I imagine it's a flaw in the parser that Quail uses, but that seems a bit out of scope for us to solve?

**Potential Fix - Cast to Array in UDOIT**
We could also cast the colors Object to an Array and just ignore the fact that there is something wrong with Quail. The only problem here is that the keys won't match up with the way we are processing each color in the array.

If you look closely at the incorrect Object, the keys are 0 and 2. This will cause an issue as we use a count to work through all the elements instead of using a foreach to loop through them.

I think that would additionally have to switch this counter based logic to a foreach loop. 

**Files For Review**
I've got a branch available in my fork that you can take a look at if you want. It's got a lot of extra debug lines in there, so it's not fit for a PR, but can at least show you what I am talking about
  - [Contrast Bug Branch](https://github.com/cooperfellows/UDOIT/tree/bug-fix-explore)
    - Again, this branch is meant only for my testing, so it's ugly.

**Comment by bagofarms** [comment] 2018-02-21 16:19
I know this issue is 2 years old, but I have confirmed that it no longer affects version 2.3.1 of UDOIT.

**Closed by bagofarms** 2018-02-21 16:19 UTC
Labels: bug
