### ISSUE TITLE
Video Playback continues when "View the source of the issue" is closed

### ISSUE THREAD

**Issue by mkattut** [ucfopen/UDOIT#307] opened 2017-09-28 15:10 UTC
(Hi all. New to Github. Please forgive and correct me, if I'm speaking where I'm not supposed to.)
When a course generates a "Synchronized captions should be provided for prerecorded web-based video" result, if someone clicks the "View the source of the issue" button and begins watching the video then closes the issue source, the video continues to play. 

I don't expect that this behavior is an issue for many, but I could see it as being an issue for someone with cognitive disabilities. Is there a way where the video playback can be paused or stopped when the "Close the issue" is pressed?

[Video Playback.zip](https://github.com/ucfopen/UDOIT/files/1341370/Video.Playback.zip)

**Comment by bagofarms** [comment] 2017-10-18 14:16
Thanks for reporting this!  I've marked it as a bug since this is not expected behavior.

**Comment by iturgeon** [comment] 2017-11-16 03:42
I believe the videos are embedded (and loaded) in the page the minute the report is finished.  The videos are "hidden" but not removed from the dom.  That's probably related to why they continue playing when hidden.

I'd suggest the fix lean toward loading/unloading them.  Especially since a course can contain quite a few videos - and present a rather heavy load.  

The other option would be to actively attempt to pause them when hidden.

**Closed** 2021-05-17 22:08 UTC
Labels: bug
