### ISSUE TITLE
Receiving "Session authentication failed" upon launch from within Canvas Test

### ISSUE THREAD

**Issue by mrash2** [ucfopen/UDOIT#751] opened 2022-01-28 15:53 UTC
We have installed UDOIT 3.0 on our own server, generated developer and LTI keys, and installed the app in our hosted Canvas Test environment at utk.test.instructure.com. In .env.local, we have set:
`JWK_BASE_URL = "https://utk.test.instructure.com/"` 
and in the LTI key, I have set the JWK URL to 
`https://utk.test.instructure.com/api/lti/security/jwks`

After adding the app to a course navigation, launching the app results in:
`{"message":"Session authentication failed."}`

Any suggested things to check in Canvas and/or in our app/server config?

**Comment by rob-3** [comment] 2022-01-31 14:18
Check your LTI key values and make sure they match what we have [here](https://github.com/ucfopen/UDOIT/blob/main/INSTALL_CANVAS.md#create-an-lti-developer-key).

**Comment by rob-3** [comment] 2022-01-31 14:20
If that's not the issue, if you are able to open the `Network` tab in your developer tools and reload the UDOIT page, I'm curious if you have a `/authorize` request to the above URL or to somewhere else.

**Comment by mrash2** [comment] 2022-01-31 14:27
Looks like the values match. Here's a screenshot of the Network tab. I'm assuming the red line with the 401 is where the problem occurs. 
![image](https://user-images.githubusercontent.com/59924812/151811372-e8298170-9107-4d00-9655-d93141efb086.png)

**Comment by rob-3** [comment] 2022-01-31 14:34
It appears that the issue originates in the `src/Security/SessionAuthenticator.php` file; that's the only place in the codebase with the string you reported. Can you report the exact commit you have installed?

**Comment by rob-3** [comment] 2022-01-31 14:36
Also, are you running in `dev` or `prod` mode? We've had some issues running things in `dev` mode and are running `prod` even for development temporarily while we sort them out.

**Comment by mrash2** [comment] 2022-01-31 15:02
We were in dev mode but updated to prod with the same result. I also deleted and re-added the app in Canvas just in case. Here's the Network tab this time. For some reason we're still getting a 401 Unauthorized error during authentication. 
![image](https://user-images.githubusercontent.com/59924812/151816982-f2fdace1-8b68-4774-bb1c-e0c8015f8fc1.png)

Also we are running commit d19ef66a7fd70d45f85d17b1ba1ec6e4c3a64f65

**Comment by rob-3** [comment] 2022-01-31 15:07
If you click the red request for more details, what headers/payload is being sent?

**Comment by mrash2** [comment] 2022-01-31 15:26
![image](https://user-images.githubusercontent.com/59924812/151821326-ef351278-3bba-4e85-adab-c42a967fcd77.png)
![image](https://user-images.githubusercontent.com/59924812/151821473-cf0bff18-9378-4ab6-a6c6-8101164268fe.png)
![image](https://user-images.githubusercontent.com/59924812/151821568-78249a48-c84f-437d-89f5-ed4d0adf7f91.png)

**Comment by rob-3** [comment] 2022-01-31 15:31
Are you using Edge? If so, try Chrome and see if that causes anything to change or if you get the same message

**Comment by mrash2** [comment] 2022-01-31 15:34
Yes, I use Edge. I just tried both Chrome and Safari with the same message.

**Comment by rob-3** [comment] 2022-01-31 15:46
Our test instance is currently down, so it may be a few days until I can investigate this in depth. If you discover any new pertinent details or resolve this issue in the meantime, feel free to mention that here. If you want to debug this yourself, I would look into `config/packages/security.yaml`, where you can remove authentication temporarily, and `src/Security/SessionAuthenticator.php". You could also try the `dev/v3-2-0` branch and see if that resolves the issue.

**Comment by mrash2** [comment] 2022-02-03 13:50
I'm not sure if this is a clue, but we get the same "Session authentication failed" message even if we navigate directly to https://udoit-dev.oit.utk.edu/dashboard without going through Canvas Test. I wouldn't expect the dashboard to actually display, but I didn't expect to see the same message.

**Comment by mrash2** [comment] 2022-02-03 18:48
Perhaps another clue? The dev log reports the following:
`./var/log/dev.log:[2022-01-26T16:44:47.170603+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"dashboard","authenticator":"App\\Security\\SessionAuthenticator"} []
./var/log/dev.log:[2022-01-26T16:44:47.170639+00:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"dashboard","authenticator":"App\\Security\\SessionAuthenticator"} []`

**Comment by rob-3** [comment] 2022-02-03 18:59
My (currently limited) understanding is that we do authentication and sessions through the database somehow (see `SessionService.php`). This authenticator should never be getting called. The docs mention that authenticators are called when the user is considered anonymous, so the error is happening somewhere before the authenticator.

What are the details of your setup? Is the database set up correctly?

My best experience getting it working was through Heroku, and you could try deploying to Heroku and checking if you still get the issue with it set up there.

**Comment by bagofarms** [comment] 2022-02-04 14:12
@mrash2 From what I'm reading, web server configurations can lead to this issue.  Another institution posted their NGINX config that you might find helpful: https://github.com/tl-its-umich-edu/UDOIT/blob/main/config/nginx_app.conf

**Comment by mrash2** [comment] 2022-02-09 21:06
Is it normal for the logs to indicate `[base_url]/api/lti/authorize?client_id=[our LTI client ID]` ?

**Comment by cdcnorton** [comment] 2022-02-10 14:50
I am working with Mark on the udoit install.
I am attaching the data from the nginx error log and access log. This is what is logged when we click on Udoit3 from inside canvas.
[udoit access log.txt](https://github.com/ucfopen/UDOIT/files/8041877/udoit.access.log.txt)
[udoit error log.txt](https://github.com/ucfopen/UDOIT/files/8041878/udoit.error.log.txt)
.

**Comment by cdcnorton** [comment] 2022-02-10 20:26
I'm helping Mark troubleshoot this issue.  Here is the web browser error after clicking on Udoit3 from canvas.
I can attach the nginx access and error logs that go along with this issue if that will help.
![image](https://user-images.githubusercontent.com/76215221/153490810-af85a9ab-6918-43b5-a147-0f15edb9ccde.png)

Thanks

**Comment by rob-3** [comment] 2022-02-10 21:05
Thanks for being persistent in getting UDOIT working! Please attach the logs you mentioned and I will take a look

**Comment by cdcnorton** [comment] 2022-02-10 21:52
Here you go
[udoit access log.txt](https://github.com/ucfopen/UDOIT/files/8044518/udoit.access.log.txt)
[udoit.error.log.txt](https://github.com/ucfopen/UDOIT/files/8044519/udoit.error.log.txt)
.

**Comment by rob-3** [comment] 2022-02-10 22:05
I think the issue might be in your database config. Are you able to access your database and send me the result of `SELECT * FROM institution;`? Please censor the `api_client_secret`, but let me know the length of it.

**Comment by cdcnorton** [comment] 2022-02-10 22:31
Yes, DB is set in the .env.local file as:
###> doctrine/doctrine-bundle ###
DATABASE_URL=mysql://udoit:******************@127.0.0.1:3306/udoit3

**Comment by rob-3** [comment] 2022-02-14 13:04
Try setting `vanity_url` in the database to `utk.test.instructure.com`

**Comment by cdcnorton** [comment] 2022-02-14 13:30
I made the vanity_url change and it had no affect, same error.  I'll get Mark to verify the api-client_secret in Canvas asap but I believe it's correct.
Thanks for your help.

**Comment by rob-3** [comment] 2022-02-14 13:42
Thanks for your determination to get UDOIT working!

We've exhausted most of the ideas I have. The only others things I would suggest are trying the Heroku setup with the instructions in `HEROKU.md` to see if that is also broken, and trying the `dev/v3-2-0` or `dev/v3-3-0`, which are both much newer than `main`. I'll be working on #776 this week, which will be replacing this authentication system anyway, so perhaps I'll discover or fix the issue then.

**Comment by rob-3** [comment] 2022-02-14 14:19
The `main` branch is the release version, the `dev/vx-x-x` branches are the unstable development branches. Usually I would suggest `main`, but `dev/v3-2-0` is frozen for release and it would be good to make sure we can still reproduce this with all the current fixes and changes.

**Comment by cdcnorton** [comment] 2022-02-18 19:34
I have a question that may or may not be related to this.  When we have APP_ENV=dev in the .env.local file, the base install seems to be working properly.  http://servername/  brings up the Symfony webpage. http://servername/lti/config pulls up like so:
{"title":"UDOIT 3","scopes":[],"extensions":[{"domain":"udoit-dev.oit.utk.edu","tool_id":"cidilabs_udoit3","platform":"canvas.instructure.com","settings":{"text":"UDOIT 3","platform":"canvas.instructure.com","placements":[{"text":"UDOIT 3","placement":"course_navigation","message_type":"LtiResourceLinkRequest","target_link_uri":"https:\/\/udoit-dev.oit.utk.edu\/dashboard","visibility":"admins","enabled":true,"default":"disabled"},{"text":"UDOIT 3 Admin","placement":"account_navigation","message_type":"LtiResourceLinkRequest","target_link_uri":"https:\/\/udoit-dev.oit.utk.edu\/admin","enabled":true}]},"privacy_level":"anonymous"}],"public_jwk":[],"description":"User settings for UDOIT 3.x","public_jwk_url":"https:\/\/canvas.instructure.com\/api\/lti\/security\/jwks","target_link_uri":"https:\/\/udoit-dev.oit.utk.edu\/dashboard","oidc_initiation_url":"https:\/\/udoit-dev.oit.utk.edu\/lti\/authorize","custom_fields":{"lms_id":"canvas","lms_user_id":"$Canvas.user.id","lms_course_id":"$Canvas.course.id","lms_account_id":"$Canvas.account.id","lms_api_domain":"$Canvas.api.domain"}}

Even a info.php page in the public directory pulls up properly.

When I change to APP_ENV=prod in the .env.local file and try to http://servername/ it breaks. The Symfony page is no longer accessable.
We get:

Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Why would changing that in param cause this?

**Comment by cdcnorton** [comment] 2022-02-18 20:25
FYI - We have gotten further with our rhel 8 server running with APP_ENV=dev. We are able to connect to the Udoit server and authenticate. Now we are troubleshooting this error:


![Screenshot 2022-02-18 152435](https://user-images.githubusercontent.com/76215221/154756266-90f29331-77e6-4cd8-bec2-29b6aa5157a2.jpg)

**Comment by rob-3** [comment] 2022-02-21 13:18
That sounds like a database issue. Have you tried running the migration or looking at the database manually?

Unfortunately, we don't currently have an installation working outside of Heroku, although some other schools might. I'm working on updating our Docker configuration to work, and when that is complete, it will be the supported installation method. With any luck, it will release in v3.3.0, which is planned to release at the end of March, and much sooner in dev.

**Comment by cdcnorton** [comment] 2022-02-21 14:24
I ran the migration steps in the install doc.
php bin/console doctrine:database:create
php bin/console doctrine:migrations:migrate
php bin/console cache:warmup --env=prod

DB info:
MariaDB [udoit3]> show tables;
+--------------------+
| Tables_in_udoit3   |
+--------------------+
| content_item       |
| course             |
| file_item          |
| institution        |
| issue              |
| log_entry          |
| messenger_messages |
| migration_versions |
| report             |
| user_session       |
| users              |
+--------------------+
11 rows in set (0.001 sec)

FYI - MariaDB [udoit3]> desc content_item;
+----------------+--------------+------+-----+---------+----------------+
| Field | Type | Null | Key | Default | Extra |
+----------------+--------------+------+-----+---------+----------------+
| id | int(11) | NO | PRI | NULL | auto_increment |
| course_id | int(11) | NO | MUL | NULL | |
| title | varchar(255) | NO | | NULL | |
| content_type | varchar(255) | NO | | NULL | |
| lms_content_id | varchar(512) | NO | | NULL | |
| updated | datetime | NO | | NULL | |
| metadata | longtext | YES | | NULL | |
| published | tinyint(1) | NO | | NULL | |
| active | tinyint(1) | NO | | NULL | |
| body | longtext | YES | | NULL | |
| url | varchar(255) | YES | | NULL | |
+----------------+--------------+------+-----+---------+----------------+
11 rows in set (0.001 sec)

Should I run the 3 steps again?

**Comment by rob-3** [comment] 2022-02-21 14:26
It may be worth a shot, but at this point I would recommend just waiting until I finish writing the new `Dockerfile` that should make this more or less a "one-click" install and sort out setup issues. I'll be working on it all week until it is done and I can let you know when it lands in `dev` if you want.

**Comment by cdcnorton** [comment] 2022-02-21 21:45
Looks like this might have been a course/Sandbox issue. Tested on a 2nd course and it seemed to work fine. We are going to test a few more course to verify.  Thanks for the help.

**Comment by mrash2** [comment] 2022-02-22 14:35
We're still not sure of the original issue that caused the authentication problem, but installing 3.3 on a RHEL 8 server and it seems to have taken care of it. As @cdcnorton mentioned, we were having a new problem with the new instance where we got the exception error listed above upon scanning a course. This error seems to be isolated to a specific Canvas course, although I have yet to identify what might be unique about that course and/or the content within it. The app seems to be working in other courses in Canvas Test.

**Comment by rob-3** [comment] 2022-02-22 18:55
> Looks like this might have been a course/Sandbox issue. Tested on a 2nd course and it seemed to work fine. We are going to test a few more course to verify. Thanks for the help.

Sure thing!

> We're still not sure of the original issue that caused the authentication problem, but installing 3.3 on a RHEL 8 server and it seems to have taken care of it. As @cdcnorton mentioned, we were having a new problem with the new instance where we got the exception error listed above upon scanning a course. This error seems to be isolated to a specific Canvas course, although I have yet to identify what might be unique about that course and/or the content within it. The app seems to be working in other courses in Canvas Test.

I'm going to close this issue, but if you can get more details on this other issue so I can reproduce, please file a new issue.

**Closed by rob-3** 2022-02-22 18:55 UTC
Labels: bug

**Comment by mrash2** [comment] 2022-02-23 16:40
> The `main` branch is the release version, the `dev/vx-x-x` branches are the unstable development branches. Usually I would suggest `main`, but `dev/v3-2-0` is frozen for release and it would be good to make sure we can still reproduce this with all the current fixes and changes.

When do you expect v3-2-0 to move over to main? I think that one adds the messaging about handling iframes, right?

**Comment by rob-3** [comment] 2022-02-23 17:25
We're targeting the end of the month, but @bagofarms makes the final decision.

**Comment by bagofarms** [comment] 2022-02-23 18:32
Sorry about the delay.  I've been extremely busy with other aspects of my job for the last few months, so I haven't been able to spend as much time as I would like on UDOIT.  I basically just need to do some final manual tests on 3.2.0 to make sure it's ready to go.  If anyone on this thread would like to perform some testing of the `dev/v3-2-0` branch, please let me know if you find any issues.  That would help a great deal.
