### ISSUE TITLE
UDOIT Admin users report needs user name

### ISSUE THREAD

**Issue by cidilabs** [ucfopen/UDOIT#540] opened 2020-06-19 17:47 UTC
The UDOIT Admin Errors screen is currently using the API to pull more information about courses and users. Can we do the same thing for the users tab? It would be helpful to know which users are actively using the tool.

**Comment by bagofarms** [comment] 2021-05-17 22:38
Duplicate of #476 , closing

**Closed by bagofarms** 2021-05-17 22:38 UTC
Labels: enhancement
